apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - ../../base/todo-api/deployment.yaml
  - ../../base/todo-api/service.yaml
  - ../../base/todo-api/configmap.yaml

patches:
  - path: todo-api-patch.yaml